-- AddForeignKey
ALTER TABLE "Order" ADD CONSTRAINT "Order_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Order" ADD CONSTRAINT "Order_orderedBooks_fkey" FOREIGN KEY ("orderedBooks") REFERENCES "Book"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
